### ISSUE TITLE
Function clkPulseLength() doesn't work correctly with "gcc -O2" compiler option

### ISSUE THREAD

**Issue by jorgedsmatias** [vogelchr/radioclkd2#12]
I have submitted a working Pull Request #11 this incorrect behaviour.
The problem was noticed with a Raspberry Pi 3 running Debian Bullseye (32bit and 64bit) which comes with GCC v10.2.1

**Comment by vogelchr** [comment]
I've seen the pull request, and applied it already. Many thanks.
